# Generated by Django 5.2.17 on 2026-10-01 03:47

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assistant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Limit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(unique=True)),
                ('user_free', models.PositiveBigIntegerField(blank=True, null=True)),
                ('user_premium', models.PositiveBigIntegerField(blank=True, null=True)),
                ('system', models.PositiveBigIntegerField(blank=True, null=True)),
                ('period', models.CharField(choices=[('month', 'Calendar month'), ('day', 'Calendar day'), ('total', 'All time')], max_length=5)),
                ('enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('amount', models.PositiveBigIntegerField(default=1)),
                ('refunded', models.BooleanField(default=False)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ask', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to='assistant.askquery')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'key', 'created_at'], name='usage_user_key_created'), models.Index(fields=['key', 'created_at'], name='usage_key_created')],
            },
        ),
    ]
