# Generated by Django 5.2.17 on 2026-09-30 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event', models.CharField(choices=[('google_login_succeeded', 'Google sign-in succeeded'), ('google_login_failed', 'Google sign-in failed'), ('login_blocked', 'Sign-in blocked (rate limited)'), ('signed_up', 'Signed up'), ('logged_out', 'Logged out'), ('device_signed_out', 'Device signed out')], max_length=32)),
                ('email', models.CharField(blank=True, max_length=254)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('request_id', models.CharField(blank=True, max_length=64)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'created_at'], name='accounts_se_event_527d15_idx')],
            },
        ),
    ]
