# Generated by Django 5.2.17 on 2026-10-01 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_signedindevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='app_open_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='memory_choice_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='memory_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='memory_notice_seen_at_open',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=64),
        ),
    ]
