# Generated by Django 5.2.17 on 2026-10-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_lifecycle_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='signedindevice',
            name='last_app_open_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
