# Generated by Django 5.2.17 on 2026-10-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_pushsubscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="memory_reset_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
