# Generated by Django 5.2.17 on 2026-09-30 17:23

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import notes.content
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('text', 'Text'), ('checklist', 'Checklist')], default='text', max_length=10)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.JSONField(default=notes.content.empty_doc)),
                ('content_text', models.TextField(blank=True, editable=False)),
                ('version', models.PositiveIntegerField(default=1)),
                ('revision', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['owner', 'revision'], name='note_owner_revision'), models.Index(fields=['owner', '-id'], name='note_owner_id'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'content_text', config='english'), name='note_fts')],
            },
        ),
    ]
