# Generated by Django 5.2.17 on 2026-10-01 04:03

import django.db.models.deletion
import notes.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_at', models.DateTimeField()),
                ('lead_days', models.PositiveSmallIntegerField(default=7)),
                ('channels', models.JSONField(default=notes.models.default_reminder_channels)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='scheduled', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='notes.note')),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReminderDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurrence_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('channel_results', models.JSONField(blank=True, default=dict)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notes.reminder')),
            ],
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['status', 'due_at'], name='reminder_status_due'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['owner', 'due_at'], name='reminder_owner_due'),
        ),
        migrations.AddConstraint(
            model_name='reminder',
            constraint=models.CheckConstraint(condition=models.Q(('lead_days__lte', 30)), name='reminder_lead_days_max'),
        ),
        migrations.AddConstraint(
            model_name='reminderdelivery',
            constraint=models.UniqueConstraint(fields=('reminder', 'occurrence_at'), name='reminder_delivery_once'),
        ),
    ]
