# Generated by Django 5.2.17 on 2026-10-01 09:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_formatjob"),
        ("notes", "0002_reminders"),
    ]

    operations = []
