# Generated by Django 5.2.17 on 2026-10-01 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limits', '0002_backfill_ask_usage'),
        ('notes', '0004_attachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='note',
            name='summary_version',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='SummaryJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_version', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('error_code', models.CharField(blank=True, max_length=50)),
                ('error', models.CharField(blank=True, max_length=255)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('model', models.CharField(blank=True, max_length=100)),
                ('prompt_version', models.CharField(blank=True, max_length=50)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('idempotency_key', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='summary_jobs', to='notes.attachment')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='summary_jobs', to='notes.note')),
                ('owner', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='summary_jobs', to=settings.AUTH_USER_MODEL)),
                ('usage_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='limits.usageevent')),
            ],
            options={
                'indexes': [models.Index(fields=['owner', '-id'], name='summaryjob_owner_id'), models.Index(fields=['status', 'created_at'], name='summaryjob_status_created')],
                'constraints': [models.UniqueConstraint(fields=('owner', 'idempotency_key'), name='summaryjob_owner_idempotency_key')],
            },
        ),
    ]
