# Generated by Django 5.2.17 on 2026-10-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_conversations"),
    ]

    operations = [
        migrations.AddField(
            model_name="askquery",
            name="partial_answer",
            field=models.TextField(blank=True),
        ),
    ]
