# Generated by Django 5.2.17 on 2026-10-01 09:30

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0002_conversations"),
        # CREATE EXTENSION vector, for the embedding column.
        ("retrieval", "0001_vector_extension"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserFact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[("static", "Static"), ("dynamic", "Dynamic")],
                        default="static",
                        max_length=10,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=1536)),
                ("embedding_model", models.CharField(max_length=200)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "source_ask",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="assistant.askquery",
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supersedes",
                        to="assistant.userfact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    pgvector.django.indexes.HnswIndex(
                        ef_construction=64,
                        fields=["embedding"],
                        m=16,
                        name="fact_embedding_hnsw",
                        opclasses=["vector_cosine_ops"],
                    ),
                    models.Index(fields=["user", "superseded_by"], name="fact_user_superseded"),
                ],
            },
        ),
    ]
