# Generated by Django 5.2.17 on 2026-10-01 13:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("assistant", "0003_partial_answer"),
        ("assistant", "0003_userfact"),
    ]

    operations = []
