# Generated by Django 5.2.17 on 2026-10-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assistant", "0004_merge_0003_partial_answer_0003_userfact"),
    ]

    operations = [
        migrations.AddField(
            model_name="askquery",
            name="memory_used",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
