# Generated by Django 5.2.17 on 2026-09-30 18:42

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('notes', '0001_note'),
        ('retrieval', '0001_vector_extension'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('heading_path', models.TextField(blank=True)),
                ('content_hash', models.CharField(max_length=64)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536)),
                ('embedding_model', models.CharField(max_length=200)),
                ('note_version', models.PositiveIntegerField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='notes.note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_chunks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['note_id', 'ordinal'],
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chunk_embedding_hnsw', opclasses=['vector_cosine_ops']), models.Index(fields=['owner', 'note'], name='chunk_owner_note'), django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('heading_path', 'text', config='english'), name='chunk_fts')],
            },
        ),
    ]
