# Generated by Django 5.2.17 on 2026-10-01 13:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_attachment"),
        ("retrieval", "0002_notechunk"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notechunk",
            name="attachment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chunks",
                to="notes.attachment",
            ),
        ),
        migrations.AddField(
            model_name="notechunk",
            name="source",
            field=models.CharField(
                choices=[
                    ("note", "Note"),
                    ("attachment", "Attachment"),
                    ("summary", "Summary"),
                ],
                default="note",
                max_length=10,
            ),
        ),
        migrations.AddConstraint(
            model_name="notechunk",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("attachment__isnull", False), ("source", "attachment")),
                    models.Q(
                        models.Q(("source", "attachment"), _negated=True),
                        ("attachment__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="chunk_attachment_iff_source",
            ),
        ),
    ]
